using System.Text.RegularExpressions;

namespace OrderPlatform.Migrations.Tests;

public enum ScriptKind
{
    Expand,
    Contract,
}

/// <summary>A DbUp script of one schema, e.g. <c>expand/0001_create_migrator_runs.sql</c>.</summary>
public sealed record MigrationScript(string Schema, ScriptKind Kind, string FileName, string Sql)
{
    public string Name => $"{(Kind == ScriptKind.Expand ? "expand" : "contract")}/{FileName}";
}

/// <summary>
/// The expand/contract and online-safety rules of ADR-0009 as executable checks. Each method returns the violations as
/// readable messages; an empty list means the script is allowed.
/// </summary>
public static partial class MigrationRules
{
    /// <summary>Rules for hand-written DbUp scripts.</summary>
    /// <param name="script">The script to check.</param>
    /// <param name="schemaScripts">All scripts of the same schema (for the NOT NULL and contract reference rules).</param>
    public static IReadOnlyList<string> CheckScript(MigrationScript script, IReadOnlyCollection<MigrationScript> schemaScripts)
    {
        var violations = new List<string>();
        var statements = SqlText.Statements(script.Sql);
        var body = statements.Where(statement => !IsSet(statement) && !IsTransactionControl(statement)).ToList();

        if (!statements.Any(statement => LockTimeout().IsMatch(statement)))
        {
            violations.Add("sets no lock_timeout (add: SET lock_timeout = '5s';)");
        }

        if (body.Any(statement => Concurrently().IsMatch(statement)))
        {
            if (body.Count > 1 || statements.Any(IsTransactionControl))
            {
                violations.Add("CREATE INDEX CONCURRENTLY must be the only statement in its script, without BEGIN/COMMIT");
            }
        }
        else if (body.Count > 1 && !(statements.Any(statement => statement is "begin" or "start transaction") && statements.Any(statement => statement is "commit" or "end")))
        {
            violations.Add($"has {body.Count} statements but no explicit BEGIN; ... COMMIT; (DbUp runs without a transaction)");
        }

        if (script.Kind == ScriptKind.Expand)
        {
            var earlierExpandSql = string.Join(
                ";",
                schemaScripts.Where(other => other.Kind == ScriptKind.Expand && string.CompareOrdinal(other.FileName, script.FileName) <= 0)
                    .Select(other => SqlText.StripCommentsAndLiterals(other.Sql).ToLowerInvariant()));

            violations.AddRange(ExpandViolations(body, allowMartenFunctionDrops: false, notNullAllowed: column =>
                Regex.IsMatch(earlierExpandSql, $@"check\s*\(\s*""?{Regex.Escape(column)}""?\s+is\s+not\s+null\s*\)")
                && Regex.IsMatch(earlierExpandSql, @"\bvalidate\s+constraint\b")));
        }
        else
        {
            violations.AddRange(ContractReferenceViolations(script, schemaScripts));
        }

        return violations;
    }

    /// <summary>
    /// Rules for the Marten patch generated by <c>db-patch</c> against the previous release's schema (ADR-0008): it must be
    /// expand-only. Generated scripts are not checked for lock_timeout or explicit transactions.
    /// </summary>
    public static IReadOnlyList<string> CheckGeneratedPatch(string sql)
    {
        var body = SqlText.Statements(sql).Where(statement => !IsSet(statement) && !IsTransactionControl(statement)).ToList();
        return ExpandViolations(body, allowMartenFunctionDrops: true, notNullAllowed: _ => false).ToList();
    }

    private static IEnumerable<string> ExpandViolations(IReadOnlyList<string> body, bool allowMartenFunctionDrops, Func<string, bool> notNullAllowed)
    {
        var createdTables = body
            .Select(statement => CreateTable().Match(statement))
            .Where(match => match.Success)
            .Select(match => TableName(match.Groups["table"].Value))
            .ToHashSet(StringComparer.Ordinal);

        foreach (var statement in body)
        {
            var excerpt = Excerpt(statement);

            if (Drop().IsMatch(statement) && !(allowMartenFunctionDrops && MartenFunctionDrop().IsMatch(statement)))
            {
                yield return $"removes something outside a contract script: {excerpt}";
            }

            if (Rename().IsMatch(statement))
            {
                yield return $"renames outside a contract script: {excerpt}";
            }

            if (AlterType().IsMatch(statement))
            {
                yield return $"changes a column type (table rewrite, breaks the previous version): {excerpt}";
            }

            if (SetNotNull().Match(statement) is { Success: true } setNotNull && !notNullAllowed(setNotNull.Groups["column"].Value))
            {
                yield return $"SET NOT NULL without a preceding validated CHECK (\"{setNotNull.Groups["column"].Value}\" IS NOT NULL): {excerpt}";
            }

            if (CreateIndex().IsMatch(statement) && !Concurrently().IsMatch(statement)
                && IndexTable().Match(statement) is { Success: true } indexTable
                && !createdTables.Contains(TableName(indexTable.Groups["table"].Value)))
            {
                yield return $"creates an index on an existing table without CONCURRENTLY: {excerpt}";
            }

            if (AlterTable().Match(statement) is { Success: true } alter && !createdTables.Contains(TableName(alter.Groups["table"].Value)))
            {
                foreach (var clause in TopLevelClauses(alter.Groups["actions"].Value))
                {
                    foreach (var violation in AlterClauseViolations(clause))
                    {
                        yield return $"{violation}: {excerpt}";
                    }
                }
            }
        }
    }

    private static IEnumerable<string> AlterClauseViolations(string clause)
    {
        if (AddConstraint().Match(clause) is { Success: true } constraint)
        {
            var kind = constraint.Groups["kind"].Value;
            if (kind is "foreign key" or "check" && !clause.Contains("not valid", StringComparison.Ordinal))
            {
                yield return "adds a validated constraint to an existing table (add it NOT VALID, validate in a later script)";
            }
            else if (kind is "unique" or "primary key" or "exclude" && !clause.Contains("using index", StringComparison.Ordinal))
            {
                yield return "adds a unique/primary key constraint without USING INDEX (build the index CONCURRENTLY first)";
            }

            yield break;
        }

        if (AddColumn().Match(clause) is not { Success: true } column)
        {
            yield break;
        }

        var definition = column.Groups["definition"].Value;
        if (VolatileDefault().IsMatch(definition))
        {
            yield return "adds a column with a volatile default (rewrites the table under an exclusive lock; add it nullable and backfill)";
        }
        else if (NotNull().IsMatch(definition) && !definition.Contains("default", StringComparison.Ordinal))
        {
            yield return "adds a NOT NULL column without a DEFAULT (the previous version cannot insert rows)";
        }
    }

    private static IEnumerable<string> ContractReferenceViolations(MigrationScript script, IReadOnlyCollection<MigrationScript> schemaScripts)
    {
        var reference = CompletesReference().Match(script.Sql);
        if (!reference.Success)
        {
            yield return "contract script does not reference the expand script it completes (add: -- completes: expand/<file>.sql)";
            yield break;
        }

        var expandName = reference.Groups["script"].Value;
        if (!schemaScripts.Any(other => other.Kind == ScriptKind.Expand && other.Name == expandName))
        {
            yield return $"references {expandName}, which does not exist in schema '{script.Schema}'";
        }
    }

    /// <summary>Splits ALTER TABLE actions on commas outside parentheses.</summary>
    private static IEnumerable<string> TopLevelClauses(string actions)
    {
        var depth = 0;
        var start = 0;
        for (var i = 0; i < actions.Length; i++)
        {
            depth += actions[i] switch { '(' => 1, ')' => -1, _ => 0 };
            if (actions[i] == ',' && depth == 0)
            {
                yield return actions[start..i].Trim();
                start = i + 1;
            }
        }

        yield return actions[start..].Trim();
    }

    private static bool IsSet(string statement) => statement.StartsWith("set ", StringComparison.Ordinal);

    private static bool IsTransactionControl(string statement) => statement is "begin" or "commit" or "end" or "start transaction";

    private static string TableName(string name)
    {
        var unquoted = name.Replace("\"", "", StringComparison.Ordinal);
        return unquoted[(unquoted.LastIndexOf('.') + 1)..];
    }

    private static string Excerpt(string statement) => statement.Length <= 120 ? statement : statement[..120] + "…";

    [GeneratedRegex(@"^set\s+(local\s+)?lock_timeout\b")]
    private static partial Regex LockTimeout();

    [GeneratedRegex(@"\bconcurrently\b")]
    private static partial Regex Concurrently();

    [GeneratedRegex(@"^drop\b|\bdrop\s+(column|constraint|default|not\s+null|index|table|trigger|function|view|schema|type|sequence|policy|extension)\b")]
    private static partial Regex Drop();

    [GeneratedRegex(@"^drop\s+function\s+(if\s+exists\s+)?""?\w+""?\.""?mt_")]
    private static partial Regex MartenFunctionDrop();

    [GeneratedRegex(@"\brename\b")]
    private static partial Regex Rename();

    [GeneratedRegex(@"^alter\s+table\b.*\balter\s+(column\s+)?""?\w+""?\s+(set\s+data\s+)?type\b")]
    private static partial Regex AlterType();

    [GeneratedRegex(@"\balter\s+(column\s+)?""?(?<column>\w+)""?\s+set\s+not\s+null\b")]
    private static partial Regex SetNotNull();

    [GeneratedRegex(@"^create\s+(unique\s+)?index\b")]
    private static partial Regex CreateIndex();

    [GeneratedRegex(@"\bon\s+(only\s+)?(?<table>[\w"".]+)")]
    private static partial Regex IndexTable();

    [GeneratedRegex(@"^create\s+(unlogged\s+)?table\s+(if\s+not\s+exists\s+)?(?<table>[\w"".]+)")]
    private static partial Regex CreateTable();

    [GeneratedRegex(@"^alter\s+table\s+(if\s+exists\s+)?(only\s+)?(?<table>[\w"".]+)\s+(?<actions>.*)$")]
    private static partial Regex AlterTable();

    [GeneratedRegex(@"^add\s+(constraint\s+[\w""]+\s+)?(?<kind>foreign\s+key|check|unique|primary\s+key|exclude)\b")]
    private static partial Regex AddConstraint();

    [GeneratedRegex(@"^add\s+(column\s+)?(if\s+not\s+exists\s+)?""?\w+""?\s+(?<definition>.+)$")]
    private static partial Regex AddColumn();

    [GeneratedRegex(@"\bdefault\s*\(?\s*(gen_random_uuid|uuid_generate_v\w+|now|clock_timestamp|statement_timestamp|timeofday|random|nextval)\s*\(|\bdefault\s*\(?\s*(current_timestamp|localtimestamp)\b|\b(small|big)?serial\b|\bgenerated\s+(always|by\s+default)\s+as\s+identity\b")]
    private static partial Regex VolatileDefault();

    [GeneratedRegex(@"\bnot\s+null\b")]
    private static partial Regex NotNull();

    [GeneratedRegex(@"--\s*completes:\s*(?<script>expand/[\w.\-]+\.sql)", RegexOptions.IgnoreCase)]
    private static partial Regex CompletesReference();
}
